In [9]:
import numpy as np

### Question 1

In [10]:
l2 = np.arange(1, 11)
print(l2)
l2 = np.arange(0.5, 5.0 + 0.1, 0.25)
print(l2)

[ 1  2  3  4  5  6  7  8  9 10]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


### Question 2

In [11]:
print(np.zeros(10, dtype=int))
print(np.zeros(shape=(3,4), dtype=int)) 

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Question 3

In [13]:
lin_array = np.linspace(2, 12, 5, dtype=int)
print(lin_array)
lin_array = np.linspace(3, 9, 4, dtype=int)
print(lin_array)

[ 2  4  7  9 12]
[3 5 7 9]


### Question 4

In [16]:
random_array = np.random.rand(2, 4)
print('np.random.rand(2, 4):\n', random_array)
random_int = np.random.randint(10, 21, (3, 3))
print('np.random.randint(10, 21, (3, 3)):\n',random_int)
reshaped = random_array.reshape(1, 8)
print('random_array.reshape(1, 8)',reshaped)

np.random.rand(2, 4):
 [[0.51874877 0.21951943 0.98060486 0.62995853]
 [0.65619006 0.87543825 0.18469633 0.58163861]]
np.random.randint(10, 21, (3, 3)):
 [[17 15 18]
 [18 15 10]
 [16 12 10]]
random_array.reshape(1, 8) [[0.51874877 0.21951943 0.98060486 0.62995853 0.65619006 0.87543825
  0.18469633 0.58163861]]


‫The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

source: https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

### Question 5

Using the same np.random.seed() we should get the same numbers, every time you run your code. The main use of this is tracability for debugging or when you want consistent results across multiple runs.
Or if you want to share code with others or run it on different machines, using a fixed seed ensures everyone sees the same results. 

### Question 6

In [21]:
list1 = []
for i in range(5):
    list1.append(int(input(f"input {5-i} more numbers: ")));
arr1 = np.array(list1);
print("max of arr: ", arr1.max());
print("min of arr: ", arr1.min());
print("shape of arr: ", arr1.shape);
print('argmax of arr: ', arr1.argmax());
print('argmin of arr: ', arr1.argmin());

input 5 more numbers:  100
input 4 more numbers:  5
input 3 more numbers:  0
input 2 more numbers:  -111
input 1 more numbers:  -5


max of arr:  100
min of arr:  -111
shape of arr:  (5,)
argmax of arr:  0
argmin of arr:  3
